//! Comprehensive tests for the generate_clients macro (gRPC only)

use modkit_macros::generate_clients;
use tonic::transport::Channel;

// Mock tonic client type for testing
// In real usage, this would be generated by tonic from proto files
#[derive(Clone)]
pub struct MockServiceClient<T> {
    _inner: T,
}

impl MockServiceClient<Channel> {
    pub fn new(_channel: Channel) -> Self {
        Self { _inner: _channel }
    }

    // Mock gRPC method that would be generated by tonic
    #[allow(dead_code)]
    pub async fn get_item(
        &mut self,
        _req: tonic::Request<ProtoGetItemRequest>,
    ) -> Result<tonic::Response<ProtoItemResponse>, tonic::Status> {
        unimplemented!("mock for compile-time testing only")
    }

    #[allow(dead_code)]
    pub async fn list_items(
        &mut self,
        _req: tonic::Request<ProtoListItemsRequest>,
    ) -> Result<tonic::Response<ProtoItemListResponse>, tonic::Status> {
        unimplemented!("mock for compile-time testing only")
    }
}

// Proto message types (mocks)
#[derive(Clone)]
pub struct ProtoGetItemRequest {
    pub id: String,
}

#[derive(Clone)]
pub struct ProtoItemResponse {
    pub id: String,
    pub name: String,
}

#[derive(Clone)]
pub struct ProtoListItemsRequest {
    pub limit: u32,
}

#[derive(Clone)]
pub struct ProtoItemListResponse {
    pub items: Vec<ProtoItemResponse>,
}

// Domain types
#[derive(Clone, Debug)]
pub struct GetItemRequest {
    pub id: String,
}

#[derive(Clone, Debug)]
pub struct ListItemsRequest {
    pub limit: usize,
}

#[derive(Clone, Debug)]
pub struct ItemResponse {
    pub id: String,
    pub name: String,
}

// Conversion implementations (required for generated client)
impl From<GetItemRequest> for ProtoGetItemRequest {
    fn from(req: GetItemRequest) -> Self {
        ProtoGetItemRequest { id: req.id }
    }
}

impl From<ProtoItemResponse> for ItemResponse {
    fn from(proto: ProtoItemResponse) -> Self {
        ItemResponse {
            id: proto.id,
            name: proto.name,
        }
    }
}

impl From<ListItemsRequest> for ProtoListItemsRequest {
    fn from(req: ListItemsRequest) -> Self {
        ProtoListItemsRequest {
            limit: req.limit as u32,
        }
    }
}

impl From<ProtoItemListResponse> for Vec<ItemResponse> {
    fn from(proto: ProtoItemListResponse) -> Self {
        proto.items.into_iter().map(Into::into).collect()
    }
}

// Test 1: gRPC client generation
#[generate_clients(grpc_client = "crate::MockServiceClient<tonic::transport::Channel>")]
#[async_trait::async_trait]
pub trait TestApi: Send + Sync {
    async fn get_item(&self, req: GetItemRequest) -> Result<ItemResponse, anyhow::Error>;
    async fn list_items(&self, req: ListItemsRequest) -> Result<Vec<ItemResponse>, anyhow::Error>;
}

#[test]
fn test_generate_clients_macro_compiles() {
    // This test passes if the macro-generated code compiles successfully
}

#[test]
fn test_grpc_client_struct_exists() {
    // Verify the generated client struct exists
    let _type_check = |_: TestApiGrpcClient| {};
}

#[test]
fn test_grpc_client_has_connect_method() {
    // Verify connect method signature exists (compile-time check)
    let _fn_check: fn(String) -> _ = TestApiGrpcClient::connect;
}

#[test]
fn test_grpc_client_has_from_channel_method() {
    // Verify from_channel method exists (compile-time check)
    let _fn_check: fn(Channel) -> TestApiGrpcClient = TestApiGrpcClient::from_channel;
}

// Test 2: Single method API
#[generate_clients(grpc_client = "crate::SimpleMockClient<tonic::transport::Channel>")]
#[async_trait::async_trait]
pub trait SimpleApi: Send + Sync {
    async fn ping(&self, msg: String) -> Result<String, anyhow::Error>;
}

#[derive(Clone)]
pub struct SimpleMockClient<T> {
    _inner: T,
}

impl SimpleMockClient<Channel> {
    pub fn new(_channel: Channel) -> Self {
        Self { _inner: _channel }
    }

    #[allow(dead_code)]
    pub async fn ping(
        &mut self,
        _req: tonic::Request<String>,
    ) -> Result<tonic::Response<String>, tonic::Status> {
        unimplemented!("mock")
    }
}

#[test]
fn test_simple_api_compiles() {
    // Verify single-method API generates correctly
    let _type_check = |_: SimpleApiGrpcClient| {};
}
